import "./globals.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "UM Arendus",
  description: "Generated by UM Arendus",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
      </head>
      <body className="antialiased">
        {children}
      </body>
    </html>
  );
}
